### ISSUE TITLE
Ability to save / load sessions / captures

### ISSUE THREAD

**Issue by smunaut** [usb-tools/ViewSB#10]
Pretty much self explanatory why this is useful :p

The iti1480a capture format seems to have been adopted by a few projects ... although tbh that format is a bit weird to me.

**Comment by ktemkin** [comment]
I'd love to have this added when I (or others) have time. 

I was considering using a format like SQLite as the native/internal format and then allowing easy export to various formats (e.g. USB Pcap, iti1480a). Using something targeted as a database as the internal representation would allow for easy filtering/searching, which I think is very desirable.

**Comment by mndza** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
