### ISSUE TITLE
XHC20 backend for macOS >= high sierra

### ISSUE THREAD

**Issue by bikeNomad** [usb-tools/ViewSB#24]
Apple added a USB monitoring network interface named "XHC20" in High Sierra (10.13).
TCPDump has added a link type, and
Wireshark has added support for displaying USB traffic captured from this interface.
https://www.tcpdump.org/linktypes/LINKTYPE_USB_DARWIN.html

**Comment by mndza** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
