### ISSUE TITLE
Add IRC / Discord channel to README?

### ISSUE THREAD

**Issue by mithro** [usb-tools/ViewSB#30]
I was trying to find the URL to the Discord channel and it was pretty hard.

It would be nice if the IRC channel and Discord was linked to from the README.md file.

**Comment by ktemkin** [comment]
Sounds like a good idea to me. 

@Qyriad -- would you be willing to add this? The Discord invites are your wheelhouse. :)

**Comment by lichtfeind** [comment]
I wanted to ask if the is currently a IRC or discord to ask some questions?
Mostly about decoders and how to debugging them.

**Comment by straithe** [comment]
Please join us in the GSG Discord: https://discord.gg/rsfMw3rsU8

**Comment by straithe** [comment]
Closing this issue as I have updated the readme.
