### ISSUE TITLE
Add control channel between backends, analyzer, and frontends

### ISSUE THREAD

**Issue by ktemkin** [usb-tools/ViewSB#39]
Right now, all state is created when the analyzer starts; there's no channel for the frontend to request a device connect/disconnect, start/stop analysis, and etc. etc.

An RPC interface should exist so e.g. the frontend UI can stop and start analysis on the backend; and the backend can report errors nicely to the frontend.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
