### ISSUE TITLE
Database "base class" for frontends

### ISSUE THREAD

**Issue by ktemkin** [usb-tools/ViewSB#40]
Currently, packets are delivered to each frontend; and it's up to them to decide what to do with them.

Ideally, we should provide some unified database backend that collects packets, and allows them to be searched/filtered/etc. Ideally, this would also allow saving/loading (#10) by backing the database with a disk file.

SQLite seems like an obvious choice.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
