### ISSUE TITLE
Show packet exact time

### ISSUE THREAD

**Issue by smunaut** [usb-tools/ViewSB#6]
At least in the tui interface I couldn't see the exact time a packet has been received ( frame # + microseconds ). That's definitely useful info to check if it's expected a device responded with NAK or not.

**Comment by smunaut** [comment]
This is what I've been using in the mean time.

It's not ideal because it's only a microsecond number and having something like "Frame N + t us" would be much better, but that requires all the backends to actually provide that info (or at least the SoF). Or maybe just create a USBTimestamp type and use that instead of 'long' for the timestamp field and then have that type allow either raw time number or Frame No + offset and let the backend generate what it prefers ?  (although the custom type would be useful to customize the display of that type as well)

```diff
diff --git a/viewsb/packet.py b/viewsb/packet.py
index 122a621..8b804db 100644
--- a/viewsb/packet.py
+++ b/viewsb/packet.py
@@ -266,7 +266,7 @@ class ViewSBPacket:
                               'Request': 'Get Descriptor (0x06)', 'Index:' 0, 'Value': 'Device Descriptor (0x100)',
                               'Length': '18'  })]
         """
-        return [(self.summarize(), {'Data': self.summarize_data()})]
+        return [(self.summarize(), {'Timestamp': self.timestamp, 'Data': self.summarize_data()})]
 
 
     def get_raw_data(self):
```

**Comment by ktemkin** [comment]
Right now, we have the backends providing their own timestamps -- some (e.g. OpenVizsla) should be tagging their packets with timestamps themselves. 

It might be good to expose a function that makes the last SOF 'timestamp' to the backends; so they can use that to adjust their own timestamps in a way that makes sense.

**Comment by mndza** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
