### ISSUE TITLE
Add File backend

### ISSUE THREAD

**Issue by FFY00** [usb-tools/ViewSB#60]
It would be cool to be able to read `pcap`/`pcapng` files.

**Comment by FFY00** [comment]
Possible supporting libraries:
https://github.com/rshk/python-pcapng
https://github.com/Flameeyes/usbmon-tools

**Comment by fvdpol** [comment]
Hi Filipe, you may want to check my pull request #84 for an initial implementation of a backend that can read pcap files (validated with pcap files generated by the OpenVizsla capture device)

**Comment by FFY00** [comment]
Thank, you. I think the PR looks good overall, but there are some questions that I think should be raised regarding the architecture, and if this feature could be built-in and available on all backends.

Currently, it is not super clear who's effectively maintaining this project. I would be happy to help out but can't be the main maintainer, nor do I think that's what GSG would want. @straithe would you be able to let us know what is the current status? Maybe it makes sense to open an issue about this if there are further questions.

**Comment by fvdpol** [comment]
A proper persistence functionality to save and load state is what really is needed for ViewSB; saw this is listed as one of the items on the backlog/roadmap…..but unfortunate limited progress in this project recently. 

The pcap file backend was for me the easiest and cleanest way to revisit my analysis (reverse engineering….) without needing to reproduce same events using hardware. So sort of the minimum to make ViewSB for my specific use-case 😀

The hierarchical grouping of packets that ViewSB offers is really helpful in protocol analysis, but wish it were at similar functional (and performance) level as Wireshark. Quite a bit of work to be done on this tool though.

**Comment by mossmann** [comment]
> Currently, it is not super clear who's effectively maintaining this project.

We (Great Scott Gadgets) are maintaining ViewSB. I've moved the repository to the greatscottgadgets organization to make that clear.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
