### ISSUE TITLE
HID dissections

### ISSUE THREAD

**Issue by FFY00** [usb-tools/ViewSB#62]
Hey,

I want to add support for ViewSB to dissect HID data. Currently, all dissections are based on https://github.com/usb-tools/python-usb-protocol, which does not support HID. I have a project that can parse HID report descriptors and get the report format, https://github.com/FFY00/python-hid-parser. I was wondering if it would be alright to use it here for the dissections?

I chatted a bit about this with @Qyriad on Discord, it seems that we would generally want to get https://github.com/usb-tools/python-usb-protocol to understand HID. That is fair, but I don't think this should be *necessarily* done. HID is indeed part of the USB spec but it is used in several places outside USB, so I think having it in a separate package does make some sense. Having it as part https://github.com/usb-tools/python-usb-protocol is also a perfectly valid solution. So, what do we want to do?

Cheers :blush:,
Filipe

**Comment by mndza** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
