### ISSUE TITLE
Exceptions in frontend are silently discarded and not handled

### ISSUE THREAD

**Issue by twam** [usb-tools/ViewSB#79]
Any exceptions frontend are silently discard and not handled.

The issue is most likely that `self._pipe_recv_frontend_exception` defined in
https://github.com/usb-tools/ViewSB/blob/51c85aa483277d098658dbff809c2cbd982fa59e/viewsb/analyzer.py#L62
is nowhere used.

**Comment by FFY00** [comment]
Yes, `process_analysis_queue` should be handling these.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
