### ISSUE TITLE
backend errors interrupt tui

### ISSUE THREAD

**Issue by mossmann** [usb-tools/ViewSB#80]
Backend errors should be handled more gracefully.

**Comment by FFY00** [comment]
How do you propose this should be handled?

**Comment by FFY00** [comment]
To be clear, the current implementation on the TUI interface is not great. IMO ideally it should show the errors in a popup, I am just not sure if this is what you meant.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
