### ISSUE TITLE
Qt frontend TreeList shows packets/events out-of-sequence

### ISSUE THREAD

**Issue by fvdpol** [usb-tools/ViewSB#90]
The ViewSB grouping functionality results in events only be submitted to the visualization queue when complete. Since the Qt frontend simply appends the events to the TreeList this results in occasionally out-of-sequence visualisation:  The group is shown at 'then end', when the group is complete, instead of the start when the first packet for that group got received.

Example:
![image](https://user-images.githubusercontent.com/1499454/151151105-f0989cf2-8de2-4f92-ac26-7b12f475e9e6.png)

pcap file used:
[sequence-issue.pcap.gz](https://github.com/usb-tools/ViewSB/files/7940932/sequence-issue.pcap.gz)

Expected behavior would be that the groups/events are shown in same order they have been received/send over the wire. 

Mockup:
![image](https://user-images.githubusercontent.com/1499454/151150463-af0555d4-7fb4-4e85-b45c-06108d03363a.png)

**Comment by straithe** [comment]
Thank you for opening an issue for this. My team is a bit spread thin at the moment. If you submit a PR I'll try to get to it when I can. Otherwise, it might be a little bit before we have the people hours to do more development. I really appreciate your patience.

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
