### ISSUE TITLE
ViewSB Screenshot?

### ISSUE THREAD

**Issue by mosquito520** [usb-tools/ViewSB#95]
Does any one has screenshot of ViewSB?
cause I wish to know how does ViewSB show  USB protocol
But I'm not able to run ViewSB now
so I'm wondering is that ViewSB show usb data or format clearly?

Thanks~:)

**Comment by martinling** [comment]
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).
